select
(select sum (total) from invoice where billingcountry like "arg%" and total is not null) as Argentina,
(select sum (total) from invoice where billingcountry like "austral%" and total is not null) as Australia,
(select sum (total) from invoice where billingcountry like "austr%" and total is not null) as Austria,
(select sum (total) from invoice where billingcountry like "bel%" and total is not null) as Belgium,
(select sum (total) from invoice where billingcountry like "bra%" and total is not null) as Brazil,
(select sum (total) from invoice where billingcountry like "can%" and total is not null) as Canada,
(select sum (total) from invoice where billingcountry like "chile%" and total is not null) as Chile,
(select sum (total) from invoice where billingcountry like "cze%" and total is not null) as CzechRepublic,
(select sum (total) from invoice where billingcountry like "den%" and total is not null) as Denmark,
(select sum (total) from invoice where billingcountry like "fin%" and total is not null) as Finland,
(select sum (total) from invoice where billingcountry like "fr%" and total is not null) as France,
(select sum (total) from invoice where billingcountry like "ger%" and total is not null) as Germany,
(select sum (total) from invoice where billingcountry like "hung%" and total is not null) as Hungary,
(select sum (total) from invoice where billingcountry like "indi%" and total is not null) as India,
(select sum (total) from invoice where billingcountry like "ire%" and total is not null) as Ireland,
(select sum (total) from invoice where billingcountry like "ital%" and total is not null) as Italy,
(select sum (total) from invoice where billingcountry like "nether%" and total is not null) as Netherlands,
(select sum (total) from invoice where billingcountry like "nor%" and total is not null) as Norway,
(select sum (total) from invoice where billingcountry like "pola%" and total is not null) as Poland,
(select sum (total) from invoice where billingcountry like "portu%" and total is not null) as Portugal,
(select sum (total) from invoice where billingcountry like "spai%" and total is not null) as Spain,
(select sum (total) from invoice where billingcountry like "swede%" and total is not null) as Sweden

